version: '3.8'
services:
  app:
    network_mode: host
    build:
      context: ./monitoring-api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - prometheus
      - grafana
  prometheus:
    image: prom/prometheus
    network_mode: host
    container_name: prometheus
    ports:
      - "9091:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    network_mode: host
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
